import numpy as np
from tools import *

# a = Point(0,0,0)
# v = Vector(1,2,0)

# k = Alist(a,a)
# print(k)
# k.graft(3)
# print(k)
# k.trim(5)
# print(k)
# l = [[0,0],[1,2]]
# k = l[0][:]
# print(k)
# k = [2,2]
# print(l)
print('...')
zero = Tlist([9,9])
first = Tlist([[2.3,3],[[0,0],[[[0],[0]],[zero]]],[0,0]])
second = Tlist([1,2,3])
# print(zero)
# print(first)
# first.print_data()
# first.print_data()
# first[0]
# print(first)
# print(first.isleaf())
# first.print_data()
zero.print_data()
first.print_data()
second.print_data()
print('...')
# second = Tlist([first,[first],[[0],[0]]])
# second.print_data()
# third = Tlist([2])
# third.print_data()
# first.print_data()
# k = first.items()
# print(k)
# k.print_data()
# k.print_data()
# k[0] = 10
# k.print_data()
# first.print_data()
# k.print_data()
# k[0] = 'k'
# first.print_data()
# print(first.items())
# second.print_data()
# print(first[0][0][0])
# second = Tlist([first])
# second = Tlist(['a','b','c'])
# multi = Tlist([[0,0],[1,1],[2,2]])
# multi.print_data()
# print(original)
# m = tlist.wrap(first)
# first.print_data()
# for i in first.get_data():
#     print(i)